Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,8 +42,22 @@ jobs:
           echo "Descargando OWASP Dependency-Check..."
           curl -L "https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip" -o dependency-check.zip
 
+          
           unzip dependency-check.zip -d dependency-check
-          chmod +x dependency-check/dependency-check.sh
+          echo "Verificando estructura de archivos descomprimidos:"
+          ls -R dependency-check
+      
+          # Adjust the path to the dependency-check.sh file
+          if [ -f "dependency-check/dependency-check.sh" ]; then
+            chmod +x dependency-check/dependency-check.sh
+          elif [ -f "dependency-check/bin/dependency-check.sh" ]; then
+            chmod +x dependency-check/bin/dependency-check.sh
+          else
+            echo "❌ Error: Archivo dependency-check.sh no encontrado."
+            exit 1
+          fi
+          
+          chmod +x /dependency-check/dependency-check/bin/dependency-check.sh
           rm dependency-check.zip
 
           echo "Configurando OWASP Dependency-Check..."
@@ -63,3 +77,6 @@ jobs:
         with:
           name: reporte-dependencias
           path: ./report
+
+
+  
